### ISSUE TITLE
Date is not formatted on initializing

### ISSUE THREAD

**Issue by Rob-Post** [ng2-ui/ng2-datetime-picker#120]
See the demo plunkr: https://plnkr.co/edit/su2aiL?p=preview

The third input shows: Thu Jan 01 2015 06:00:00 GMT+0100 (W. Europe Standard Time)
In version 0.12.1 it shows: 01-01-2015 06:00

**Comment by allenhwkim** [comment]
Thanks it has been fixed and released as 0.12.6

**Comment by Rob-Post** [comment]
Thanks for the new version. I'm not using momentjs and now get an error saying `moment is not defined` when opening a date picker

**Comment by allenhwkim** [comment]
date-format should not be used if you don't use momenr

**Comment by Rob-Post** [comment]
I'm not using date-format.

I've made an example plunkr which gives the same error:
https://plnkr.co/edit/35CHLXZo3sLjjQ4sVEBc?p=preview

**Comment by Rob-Post** [comment]
Still the same error

I think only `typeof `was missing, but you also swapped the `if `and `else `block which is wrong now

**Comment by allenhwkim** [comment]
Sorry, 5 mins fix didn't go well. 0.12.9 is released again

**Comment by enheit** [comment]
Well done, now it's open. But when i try to select a day it shows another issue.
`core.umd.js?e2a5:3491 EXCEPTION: Error in ./Ng2DatetimePickerComponent class Ng2DatetimePickerComponent - inline template:33:4 caused by: moment is not defined`.

**Comment by allenhwkim** [comment]
:(, there is another bug here. 
https://github.com/ng2-ui/ng2-datetime-picker/blob/master/src/ng2-datetime-picker.component.ts#L336

I will fix and make a new release.

**Comment by Rob-Post** [comment]
When using custom formatDate() and parseDate() functions, I now get an error `string is not defined`

See this plunkr: https://plnkr.co/edit/aBguwmLkmIAD2Y4vA1vJ?p=preview

**Comment by allenhwkim** [comment]
Your plunker syntax is not correct.  https://plnkr.co/edit/2TGRytRM9UHrEuCu5jmg?p=preview
